**AI ML ASSIGNMENT NO. 14**








**NAME** - Sumit Goregaonkar


**COLLEGE** - Manav School of polytechnic


**DOMAIN** - AIML DEVELOPMENT

Q1. (Array Properties)
Create a 2D array of shape (5, 6) filled with random integers between 10 and 100.
Print the following:
1) Shape of the array  2) Total number of elements (size)  3) Data type (dtype)

In [ ]:
import numpy as np

arr = np.random.randint(10, 101, size=(5, 6))

print(arr)

[[63 99 91 94 12 37]
 [47 89 68 35 49 23]
 [75 78 37 74 50 74]
 [99 64 79 88 47 54]
 [18 10 96 70 74 70]]


Q2. (Statistical Methods - Basic)
Generate a 1D array of 20 random numbers between 1 and 50 using
np.random.randint().
Print:
1)Minimum value and its index (argmin)
 2)Maximum value and its index (argmax)
  3)Sum of all elements
   4)Mean and Standard Deviation

In [ ]:
import numpy as np

array = np.random.randint(1, 51, 20)

print("Array:")
print(array)

print("Minimum Value:", np.min(array))
print("Index of Minimum Value:", np.argmin(array))

print("Maximum Value:", np.max(array))
print("Index of Maximum Value:", np.argmax(array))

print("Sum:", np.sum(array))

print("Mean:", np.mean(array))

print("Standard Deviation:", np.std(array))

Array:
[48 18 41  9 46 21 26 24  3 21 46 28 46 44 42 48 15 16 46 35]
Minimum Value: 3
Index of Minimum Value: 8
Maximum Value: 48
Index of Maximum Value: 0
Sum: 623
Mean: 31.15
Standard Deviation: 14.290818730919513


Q3. (Statistical Methods on 2D Array)
Create a 4x5 matrix of random integers between 20 and 80.
For the entire matrix, print:
Minimum and maximum value
Sum of all elements
Mean and Standard Deviation
Then print the sum of each row and each column.

In [ ]:
import numpy as np

matrix = np.random.randint(20, 81, (4, 5))

print("Matrix:")
print(matrix)

print("Minimum Value:", np.min(matrix))
print("Maximum Value:", np.max(matrix))

print("Sum of All Elements:", np.sum(matrix))

print("Mean:", np.mean(matrix))

print("Standard Deviation:", np.std(matrix))

print("Sum of Each Row:")
print(np.sum(matrix, axis=1))

print("Sum of Each Column:")
print(np.sum(matrix, axis=0))

Matrix:
[[75 80 28 79 44]
 [71 44 62 21 68]
 [42 72 33 29 29]
 [51 79 32 42 48]]
Minimum Value: 21
Maximum Value: 80
Sum of All Elements: 1029
Mean: 51.45
Standard Deviation: 19.471710248460454
Sum of Each Row:
[306 266 205 252]
Sum of Each Column:
[239 275 155 171 189]


Q4. (Reshape)
Create a 1D array containing numbers from 1 to 24 using np.arange(())
Reshape it into (4, 6)
Reshape it into (3, 8)
Reshape it into (2, 3, 4) (3D array)
Print all reshaped arrays with their shapes.

In [ ]:
import numpy as np

array = np.arange(1, 25)

print("Original Array:")
print(array)

array1 = array.reshape(4, 6)
print("\nReshaped Array (4, 6):")
print(array1)
print("Shape:", array1.shape)

array2 = array.reshape(3, 8)
print("\nReshaped Array (3, 8):")
print(array2)
print("Shape:", array2.shape)

array3 = array.reshape(2, 3, 4)
print("\nReshaped Array (2, 3, 4):")
print(array3)
print("Shape:", array3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshaped Array (4, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshaped Array (3, 8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshaped Array (2, 3, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


Q5. (NumPy Indexing - 1D & 2D)
Create the following array:
Python
arr = np.array([[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]])
Perform the following indexing:
Extract first row
Extract last column
Extract center 2x2 submatrix
Extract all even numbers from the array using boolean indexing

In [ ]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("Original Array:")
print(arr)

print("\nFirst Row:")
print(arr[0])

print("\nLast Column:")
print(arr[:, -1])

print("\nCenter 2x2 Submatrix:")
print(arr[0:2, 1:3])

print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[20 30]
 [60 70]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


Q6. (Advanced Indexing)
Create a 5x5 matrix of random integers between 1 and 100.
Print the diagonal elements
Print elements greater than 50
Replace all elements less than 30 with 0
Print the modified array

In [ ]:
import numpy as np

matrix = np.random.randint(1, 101, (5, 5))

print("Original Matrix:")
print(matrix)

print("\nDiagonal Elements:")
print(np.diag(matrix))

print("\nElements Greater Than 50:")
print(matrix[matrix > 50])

matrix[matrix < 30] = 0

print("\nModified Matrix:")
print(matrix)

Original Matrix:
[[ 55  53  35  27  42]
 [ 44  93  76  47  66]
 [ 99 100  31  37  97]
 [ 45  19  25  49   5]
 [ 79  26  35  27  34]]

Diagonal Elements:
[55 93 31 49 34]

Elements Greater Than 50:
[ 55  53  93  76  66  99 100  97  79]

Modified Matrix:
[[ 55  53  35   0  42]
 [ 44  93  76  47  66]
 [ 99 100  31  37  97]
 [ 45   0   0  49   0]
 [ 79   0  35   0  34]]


Q7. (Arithmetic Operations) Create two arrays: a = np.array([10, 20, 30, 40]) b = np.array([1, 2, 3, 4]) Perform and print: Addition, Subtraction, Multiplication, Division Element-wise power (**) Modulo operation (%)

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

print("\nAddition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

print("\nElement-wise Power:")
print(a ** b)

print("\nModulo:")
print(a % b)

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power:
[     10     400   27000 2560000]

Modulo:
[0 0 0 0]


Q8. (Matrix Multiplication)
Create two 3x3 matrices:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])
Perform:
Element-wise multiplication (*)
Matrix multiplication (@ or np.dot())
Print both results and explain the difference in comments.

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Element-wise Multiplication:")
print(A * B)

print("\nMatrix Multiplication:")
print(A @ B)

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Q9. (Combined - Properties + Operations + Indexing)
Generate a 6x6 matrix of random numbers using np.random.randn().
Print its shape, size, and dtype.
Find the index of the maximum and minimum value.
Extract the top-left 3x3 submatrix.
Replace all negative numbers with their absolute value.
Print the mean of the modified matrix.

In [ ]:
import numpy as np

matrix = np.random.randn(6, 6)

print("Matrix:")
print(matrix)

print("\nShape:", matrix.shape)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

print("\nIndex of Maximum Value:")
print(np.unravel_index(np.argmax(matrix), matrix.shape))

print("Index of Minimum Value:")
print(np.unravel_index(np.argmin(matrix), matrix.shape))

print("\nTop-Left 3x3 Submatrix:")
print(matrix[:3, :3])

matrix = np.abs(matrix)

print("\nModified Matrix:")
print(matrix)

print("\nMean of Modified Matrix:")
print(np.mean(matrix))

Matrix:
[[ 0.90795171  2.27166493 -0.58410106 -0.11115204 -0.45622685  1.08579883]
 [-0.85984347  0.04931503 -0.49196938 -0.30404048 -0.37145203 -0.12319133]
 [ 0.29475309 -0.29838314 -0.10982005  0.61758727 -0.38985904 -0.11836996]
 [-0.98332946 -0.30185673 -0.80996185  1.15369582 -0.51260271  0.36615639]
 [ 0.51504586  0.3783864   0.14509241  2.02734288 -1.87845032  0.14915386]
 [ 2.02893723 -1.31568788  0.65957137  1.31708105  0.50334253 -0.60972993]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value:
(np.int64(0), np.int64(1))
Index of Minimum Value:
(np.int64(4), np.int64(4))

Top-Left 3x3 Submatrix:
[[ 0.90795171  2.27166493 -0.58410106]
 [-0.85984347  0.04931503 -0.49196938]
 [ 0.29475309 -0.29838314 -0.10982005]]

Modified Matrix:
[[0.90795171 2.27166493 0.58410106 0.11115204 0.45622685 1.08579883]
 [0.85984347 0.04931503 0.49196938 0.30404048 0.37145203 0.12319133]
 [0.29475309 0.29838314 0.10982005 0.61758727 0.38985904 0.11836996]
 [0.98332946 0.30185673 0.8

Q10. (Mini Project - Student Performance Analysis)
Create a NumPy-based Student Marks Analyzer:
Generate a 2D array of shape (10 students × 5 subjects) with random marks
between 30 and 100.
Print the array.
For each student, calculate total marks and average.
Find the student with highest and lowest total marks (use argmax/argmin).
Calculate overall class mean and standard deviation.
Reshape the array if needed and demonstrate indexing to extract marks of top
3 students.
Add proper comments explaining each step.

In [ ]:
import numpy as np

marks = np.random.randint(30, 101, (10, 5))

print("Student Marks:")
print(marks)

total = np.sum(marks, axis=1)

average = np.mean(marks, axis=1)

print("\nTotal Marks:")
print(total)

print("\nAverage Marks:")
print(average)

highest = np.argmax(total)
lowest = np.argmin(total)

print("\nHighest Scoring Student Index:", highest)
print("Total Marks:", total[highest])

print("\nLowest Scoring Student Index:", lowest)
print("Total Marks:", total[lowest])

print("\nClass Mean:", np.mean(marks))
print("Class Standard Deviation:", np.std(marks))

reshaped = marks.reshape(5, 10)

print("\nReshaped Array (5 x 10):")
print(reshaped)

top3 = np.argsort(total)[-3:]

print("\nTop 3 Students' Marks:")
print(marks[top3])


Student Marks:
[[41 72 70 65 89]
 [61 35 89 45 83]
 [36 90 46 60 61]
 [92 42 97 33 54]
 [54 56 81 83 59]
 [37 82 85 89 93]
 [94 54 33 65 43]
 [73 37 87 46 69]
 [76 68 59 35 98]
 [88 38 34 87 67]]

Total Marks:
[337 313 293 318 333 386 289 312 336 314]

Average Marks:
[67.4 62.6 58.6 63.6 66.6 77.2 57.8 62.4 67.2 62.8]

Highest Scoring Student Index: 5
Total Marks: 386

Lowest Scoring Student Index: 6
Total Marks: 289

Class Mean: 64.62
Class Standard Deviation: 20.698685948629684

Reshaped Array (5 x 10):
[[41 72 70 65 89 61 35 89 45 83]
 [36 90 46 60 61 92 42 97 33 54]
 [54 56 81 83 59 37 82 85 89 93]
 [94 54 33 65 43 73 37 87 46 69]
 [76 68 59 35 98 88 38 34 87 67]]

Top 3 Students' Marks:
[[76 68 59 35 98]
 [41 72 70 65 89]
 [37 82 85 89 93]]
